// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectReview.Models;

#nullable disable

namespace ProjectReview.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.CategoryProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<int>("OrderBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Density", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Density", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Phone")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime");

                    b.Property<long>("DensityId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocumentTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssign")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberPaper")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Signer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UrgencyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DensityId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UrgencyId");

                    b.ToTable("Documnet", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.DocumentType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Handler", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("Handler", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HostId")
                        .HasColumnType("bigint");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("HostId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.JobDocument", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.HasKey("JobId", "DocumentId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("JobDocument", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.JobProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Condition")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("NumberPaper")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("ProfileId");

                    b.ToTable("JobProfile", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Opinion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("JobId");

                    b.ToTable("Opinion", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.PermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PermissionGroup", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.ProfileDocument", b =>
                {
                    b.Property<long>("JobProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.HasKey("JobProfileId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ProfileDocument", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Rank", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rank", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.RolePermission", b =>
                {
                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionGroupId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Urgency", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Urgency", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RankId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Status")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PermissionGroupId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RankId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.CategoryProfile", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("Profiles")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Profile_User");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Document", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("Documents")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Documnent_User");

                    b.HasOne("ProjectReview.Models.Entities.Density", "Density")
                        .WithMany("Documents")
                        .HasForeignKey("DensityId")
                        .IsRequired()
                        .HasConstraintName("FK_Documnent_Density");

                    b.HasOne("ProjectReview.Models.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Documnent_DocumentType");

                    b.HasOne("ProjectReview.Models.Entities.Urgency", "Urgency")
                        .WithMany("Documents")
                        .HasForeignKey("UrgencyId")
                        .IsRequired()
                        .HasConstraintName("FK_Documnent_Urgency");

                    b.Navigation("CreateUser");

                    b.Navigation("Density");

                    b.Navigation("DocumentType");

                    b.Navigation("Urgency");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.DocumentType", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentType_User");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Handler", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Job", "Job")
                        .WithMany("Handlers")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Handler_Job");

                    b.HasOne("ProjectReview.Models.Entities.User", "User")
                        .WithMany("Handlers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Handler_User");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Job", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("CreateJobs")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_CreateUser");

                    b.HasOne("ProjectReview.Models.Entities.User", "Host")
                        .WithMany("HostJobs")
                        .HasForeignKey("HostId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_HostUser");

                    b.HasOne("ProjectReview.Models.Entities.User", "Instructor")
                        .WithMany("InstructorJobs")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_InstructorUser");

                    b.Navigation("CreateUser");

                    b.Navigation("Host");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.JobDocument", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Document", "Document")
                        .WithOne("JobDocument")
                        .HasForeignKey("ProjectReview.Models.Entities.JobDocument", "DocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_JobDocument_Document");

                    b.HasOne("ProjectReview.Models.Entities.Job", "Job")
                        .WithOne("JobDocument")
                        .HasForeignKey("ProjectReview.Models.Entities.JobDocument", "JobId")
                        .IsRequired()
                        .HasConstraintName("FK_JobDocument_Job");

                    b.Navigation("Document");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.JobProfile", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("JobProfiles")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_JobProfile_User");

                    b.HasOne("ProjectReview.Models.Entities.CategoryProfile", "Profile")
                        .WithMany("JobProfiles")
                        .HasForeignKey("ProfileId")
                        .IsRequired()
                        .HasConstraintName("FK_JobProfile_Profile");

                    b.Navigation("CreateUser");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Opinion", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.User", "CreateUser")
                        .WithMany("Opinions")
                        .HasForeignKey("CreateUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Opinion_User");

                    b.HasOne("ProjectReview.Models.Entities.Job", "Job")
                        .WithMany("Opinions")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Opinion_Job");

                    b.Navigation("CreateUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.ProfileDocument", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Document", "Document")
                        .WithMany("ProfileDocuments")
                        .HasForeignKey("DocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfileDocument_Document");

                    b.HasOne("ProjectReview.Models.Entities.JobProfile", "JobProfile")
                        .WithMany("ProfileDocuments")
                        .HasForeignKey("JobProfileId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfileDocument_JobProfile");

                    b.Navigation("Document");

                    b.Navigation("JobProfile");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("ProjectReview.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");

                    b.Navigation("PermissionGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.User", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Department");

                    b.HasOne("ProjectReview.Models.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("Users")
                        .HasForeignKey("PermissionGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_User_PermissionGroup");

                    b.HasOne("ProjectReview.Models.Entities.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Position");

                    b.HasOne("ProjectReview.Models.Entities.Rank", "Rank")
                        .WithMany("Users")
                        .HasForeignKey("RankId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Rank");

                    b.Navigation("Department");

                    b.Navigation("PermissionGroup");

                    b.Navigation("Position");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.UserRole", b =>
                {
                    b.HasOne("ProjectReview.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("ProjectReview.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.CategoryProfile", b =>
                {
                    b.Navigation("JobProfiles");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Density", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Document", b =>
                {
                    b.Navigation("JobDocument")
                        .IsRequired();

                    b.Navigation("ProfileDocuments");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Job", b =>
                {
                    b.Navigation("Handlers");

                    b.Navigation("JobDocument")
                        .IsRequired();

                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.JobProfile", b =>
                {
                    b.Navigation("ProfileDocuments");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.PermissionGroup", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Rank", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.Urgency", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ProjectReview.Models.Entities.User", b =>
                {
                    b.Navigation("CreateJobs");

                    b.Navigation("DocumentTypes");

                    b.Navigation("Documents");

                    b.Navigation("Handlers");

                    b.Navigation("HostJobs");

                    b.Navigation("InstructorJobs");

                    b.Navigation("JobProfiles");

                    b.Navigation("Opinions");

                    b.Navigation("Profiles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
